#line 2 "tokens.c"

#line 4 "tokens.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[317] =
    {   0,
       80,   78,   79,   77,   78,   79,   77,   79,   65,   78,
       79,   78,   79,   71,   78,   79,   64,   78,   79,   78,
       79,   59,   78,   79,   60,   78,   79,   69,   78,   79,
       68,   78,   79,   56,   78,   79,   67,   78,   79,   63,
       78,   79,   70,   78,   79,   21,   78,   79,   20,   78,
       79,   57,   78,   79,   53,   78,   79,   72,   78,   79,
       58,   78,   79,   73,   78,   79,   76,   78,   79,   18,
       78,   79,16401,   18,   78,   79,16401,   61,   78,   79,
       62,   78,   79,   74,   78,   79,   18,   78,   79,16401,
       18,   78,   79,16401,   18,   78,   79,16401,   18,   78,

       79,16401,   18,   78,   79,16401,   18,   78,   79,16401,
       18,   78,   79,16401,   54,   78,   79,   75,   78,   79,
       55,   78,   79,   66,   78,   79,   77,   78,   79,    4,
       78,   79,    6,   78,   79,   18,   78,   79,16401,   52,
       29,   38,   55,   47,   39,   36,   44,   34,   45,   35,
       46,   24,    1,    2,   37,   25,   21,   21,   21,   21,
       20,   20,   20,   20,   62,   54,   61,   43,   49,   51,
       50,   42, 8209,   18,16401,   40,   18,16401,   18,16401,
       18,16401,   18,16401,   18,16401,   18,16401,   18,16401,
       41,   48,    4,    6,    6,    6,    6,   18,16401,   29,

       22,   31,   24,    2,   25,   23,   21,   21,   21,   21,
       19,   20,   20,   20,   20,   33,   32,   18,16401,   18,
    16401,   18,16401,   18,16401,   18,16401,   18,16401,    6,
       18,16401,   24,   25,   23,   21,   19,   19,   19,   20,
       18,16401,   18,16401,   18,16401,   18,16401,   18,16401,
        6,    7, 8209,   19,   19,   26,   19,   19,   18,16401,
       18,16401,   15,   18,16401,   18,16401,   30,    7,    5,
        6,   27,   28,   26,   19,   18,16401,   18,16401,   18,
    16401,    3,    5,    6,   14,   27,   28,   18,16401,   18,
    16401,    3,   18,16401,   18,16401,   18,16401,   18,16401,

       18,16401,    8,   10,    9,   18,16401,   12,   18,16401,
       18,16401,   11,   16, 8209,   13
    } ;

static const flex_int16_t yy_accept[306] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   14,   17,
       20,   22,   25,   28,   31,   34,   37,   40,   43,   46,
       49,   52,   55,   58,   61,   64,   67,   70,   74,   78,
       81,   84,   87,   91,   95,   99,  103,  107,  111,  115,
      118,  121,  124,  127,  130,  133,  136,  140,  141,  141,
      142,  142,  143,  144,  145,  146,  146,  146,  146,  147,
      148,  149,  150,  151,  152,  152,  153,  154,  155,  156,
      157,  158,  158,  158,  159,  160,  160,  161,  162,  163,
      164,  165,  166,  167,  168,  169,  170,  171,  172,  173,
      173,  174,  176,  176,  176,  177,  179,  181,  183,  185,

      187,  189,  191,  191,  192,  193,  193,  194,  195,  195,
      195,  196,  197,  198,  200,  201,  201,  201,  201,  201,
      202,  202,  202,  202,  203,  203,  204,  205,  205,  206,
      206,  207,  208,  209,  210,  211,  211,  212,  213,  214,
      215,  216,  217,  218,  220,  222,  224,  226,  228,  230,
      230,  230,  230,  231,  233,  233,  233,  233,  233,  233,
      233,  234,  234,  235,  236,  237,  237,  237,  238,  238,
      239,  240,  241,  243,  245,  245,  247,  249,  251,  251,
      251,  251,  252,  252,  254,  254,  254,  254,  254,  254,
      254,  254,  255,  256,  256,  257,  258,  259,  261,  261,

      261,  261,  261,  261,  263,  266,  268,  269,  269,  270,
      270,  272,  272,  272,  273,  273,  274,  275,  276,  278,
      278,  278,  278,  278,  278,  278,  280,  282,  282,  283,
      283,  285,  286,  287,  288,  290,  290,  290,  290,  290,
      290,  290,  290,  292,  292,  293,  293,  293,  295,  295,
      295,  295,  295,  295,  295,  295,  297,  297,  297,  297,
      299,  299,  299,  299,  299,  299,  299,  299,  301,  301,
      301,  301,  303,  303,  303,  304,  304,  305,  306,  306,
      306,  306,  308,  309,  309,  309,  309,  309,  309,  311,
      311,  311,  311,  311,  313,  313,  313,  314,  314,  316,

      316,  316,  316,  317,  317
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   30,   30,   30,   31,   32,
       33,   33,   33,   33,   33,   34,   35,   33,   36,   37,
       33,   33,   33,   33,   38,   33,   33,   39,   33,   33,
       40,   41,   42,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   33,   33,   51,   33,   33,   52,   53,   54,
       55,   56,   33,   57,   58,   59,   60,   61,   62,   63,
       64,   33,   65,   66,   67,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[69] =
    {   0,
        1,    2,    3,    2,    1,    4,    1,    1,    1,    5,
        2,    1,    1,    1,    1,    1,    6,    1,    7,    7,
        8,    8,    1,    1,    1,    1,    1,    4,    1,    8,
        8,    8,    2,    2,    2,    2,    2,    2,    2,    1,
        4,    1,    1,    2,    7,    7,    8,    8,    8,    7,
        2,    2,    2,    9,    2,    2,    9,    2,    9,    2,
        9,    2,    9,    2,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[321] =
    {   0,
        0,   67,  762,  956,  956,  956,  731,   64,   45,   64,
      711,  697,  956,  716,   61,  956,   62,   60,   73,   89,
      136,  712,  956,   75,  712,   58,  956,   91,  111,  956,
      956,  710,  122,  128,  132,  143,  157,  173,  160,  718,
       50,  956,  956,  184,  729,  102,  195,  956,  101,  198,
      170,  956,  956,  956,  956,  141,  191,  671,  956,  956,
      956,  956,  956,  956,  708,  197,  956,    0,  956,  203,
      109,  240,  253,  204,   85,  695,  188,    0,  205,  135,
      218,  956,  956,  956,  670,  956,  956,  956,  669,  277,
      956,  280,  174,  647,  956,  283,  293,  296,  299,  309,

      312,  322,  666,  956,  956,  315,  671,  193,  636,  317,
        0,  203,  621,  339,  328,  658,   91,  286,    0,  956,
      336,    0,  609,  956,  349,  956,    0,  364,  956,  353,
      370,   80,  956,  620,  599,    0,  376,  206,  956,  616,
      586,  956,  956,  392,  395,  405,  415,  427,  431,  617,
      596,  435,  576,  437,  341,  485,  405,  526,  559,  439,
      443,  450,  460,  956,  956,  156,  171,  367,  563,  169,
      297,  956,  485,  497,  538,  516,  549,  559,  549,  266,
      441,  612,  589,  956,  323,    0,  235,    0,  548,  590,
      599,  307,  956,  464,  603,  571,  543,  625,  628,  549,

      402,  540,  538,  638,  641,  654,  956,  410,  956,  461,
        0,  574,  502,  640,  647,  659,  956,  956,  673,  531,
      531,  521,  506,  500,  456,  683,  696,  470,    0,  518,
        0,  956,  956,  956,  699,  503,  494,  487,  475,  467,
      455,  450,  702,  712,    0,  549,    0,  716,  439,  599,
      452,  429,  418,  398,  403,  726,  403,  702,  771,  730,
      390,  744,  366,  352,  343,  330,  318,  747,  314,  523,
        0,  757,  296,  299,  956,  264,  956,  956,  644,  752,
      257,  763,  956,  261,  242,  776,  241,  218,  783,  203,
      145,  124,  108,  793,  779,   86,  956,  811,  956,  796,

       74,   35,  956,  956,  855,  864,  872,  881,  887,  893,
      902,  906,  908,  910,  912,  920,  929,  938,  944,  947
    } ;

static const flex_int16_t yy_def[321] =
    {   0,
      304,    1,  304,  304,  304,  304,  304,  305,  304,  304,
      306,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  307,  307,  304,
      304,  304,  307,  307,  307,  307,  307,  307,  307,  304,
      304,  304,  304,  304,  304,  308,  307,  304,  305,  304,
      309,  304,  304,  304,  304,  306,  310,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  311,  304,  304,
       20,  304,  304,  304,  304,  312,  304,   21,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  307,  305,  306,  304,  307,  307,  307,  307,  307,

      307,  307,  304,  304,  304,  304,  304,  308,  304,  304,
      308,  308,  308,  307,  304,  304,  304,  305,  313,  304,
      306,  314,  304,  304,  304,  304,  311,  304,  304,  304,
      304,  304,  304,  304,  304,  315,  312,  304,  304,  304,
      304,  304,  304,  307,  307,  307,  307,  307,  307,  304,
      304,  304,  308,  307,  305,  305,  306,  306,  304,  304,
      304,  304,  304,  304,  304,  315,  315,  304,  304,  304,
      304,  304,  307,  307,  304,  307,  307,  307,  304,  304,
      304,  308,  304,  304,  305,  156,  306,  158,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  307,  304,  304,

      304,  304,  304,  307,  307,  307,  304,  304,  304,  316,
      317,  304,  304,  304,  304,  304,  304,  304,  307,  304,
      304,  304,  304,  304,  304,  307,  307,  316,  318,  319,
      317,  304,  304,  304,  307,  304,  304,  304,  304,  304,
      304,  304,  307,  304,  318,  316,  320,  307,  304,  304,
      304,  304,  304,  304,  304,  307,  304,  316,  316,  307,
      304,  304,  304,  304,  304,  304,  304,  307,  304,  316,
      259,  307,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  307,  304,  304,  304,  304,  304,  304,  307,  304,
      304,  304,  304,  307,  304,  304,  304,  304,  304,  304,

      304,  304,  304,    0,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304
    } ;

static const flex_int16_t yy_nxt[1025] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   22,   23,   24,   25,   26,   27,    4,   28,
       28,   28,   28,   29,   28,   28,   28,   29,   28,   30,
        4,   31,   32,   33,   28,   28,   28,   28,   28,   34,
       28,   28,   28,   35,   28,   28,   28,   36,   37,   38,
       39,   28,   28,   28,   40,   41,   42,   43,   44,   50,
       52,   53,   54,   45,   60,  104,   65,   62,   66,   66,
       66,   66,   83,   88,   89,   67,   61,   63,   64,   55,
       68,  303,   90,   90,   90,   46,   93,   84,   69,   85,

       86,   91,   47,  112,   51,   70,   50,   71,   71,   72,
       72,  116,   90,   90,   90,  105,   93,  133,  134,   73,
       94,   91,   74,   90,   90,   90,   75,   76,  302,   90,
       90,   90,   91,   90,   90,   90,  135,   73,   91,  133,
       77,   51,   91,  301,   90,   90,   90,  304,   75,  113,
      120,   76,   70,   91,   78,   78,   78,   78,   90,   90,
       90,   90,   90,   90,  297,   96,   73,   91,  140,   79,
       91,  304,   97,   80,   90,   90,   90,  296,   93,   50,
       98,   57,   94,   91,   73,  106,  141,   81,  118,  118,
      107,  222,  190,  101,  112,   80,   90,   90,   90,  115,

      115,  115,  196,   93,  112,   91,   99,  191,  102,  121,
      121,  190,  108,  100,   51,   66,   66,   66,   66,  109,
      197,   66,   66,   66,   66,  133,  191,  125,  126,  114,
      126,  116,  119,  128,  129,  116,  129,  132,  138,  132,
      113,  133,  139,  139,  120,  125,  126,  133,  126,  295,
      113,  128,  129,  122,  129,  139,   70,  117,   72,   72,
       72,   72,  293,  133,  139,  139,  130,  208,  130,  138,
       73,  131,  131,  131,  131,   57,  209,  139,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   91,   73,  292,
       91,   50,  290,   91,   90,   90,   90,   90,   90,   90,

       90,   90,   90,   91,  155,  155,   91,  241,  288,   91,
       90,   90,   90,   90,   90,   90,  106,   93,  110,   91,
      285,  107,   91,   90,   90,   90,   51,  144,   50,  115,
      115,  115,   91,   93,  193,  152,  152,  152,  152,  145,
       90,   90,   90,  108,  193,  120,   50,  284,  192,   91,
      109,  147,  283,  148,  157,  157,  193,  146,  281,  185,
      185,  116,  160,   51,  160,  116,  193,  161,  161,  161,
      161,  131,  131,  131,  131,  154,   57,  162,  149,  162,
      279,   51,  163,  163,  163,  163,  278,  117,  131,  131,
      131,  131,  167,   90,   90,   90,   90,   90,   90,  277,

      192,  164,   91,  164,  193,   91,  175,  175,  175,  168,
      276,  208,  169,  170,  120,   91,   90,   90,   90,  164,
      209,  164,  275,  187,  187,   91,  193,  171,   90,   90,
       90,  169,   90,   90,   90,  170,  181,   91,  183,   90,
       90,   91,  181,  174,  273,   57,  210,  184,  222,  269,
      173,  267,  266,  152,  152,  152,  152,  161,  161,  161,
      161,  161,  161,  161,  161,  223,  229,  176,  163,  163,
      163,  163,  265,  177,  126,  229,  126,  264,  163,  163,
      163,  163,  195,  195,  195,  195,   90,   90,   90,  178,
       50,  129,  126,  129,  126,   91,  263,  261,  199,  199,

      199,  230,  241,  186,  186,  186,  186,   91,  255,  129,
      230,  129,  242,  254,  186,  186,  186,   90,   90,   90,
      214,  214,  214,  214,  253,   51,   91,  252,  229,  186,
      186,  186,  186,  186,  186,  120,  246,  246,  251,  175,
      175,  175,  250,  198,  188,  188,  188,  188,   91,  249,
       90,   90,   90,  240,  229,  188,  188,  188,  239,   91,
       90,   90,   90,  230,  204,  238,   57,  258,  258,   91,
      188,  188,  188,  188,  188,  188,  194,  237,  194,  236,
      247,  195,  195,  195,  195,  232,  225,  200,  224,  230,
      183,   90,   90,  221,  218,  201,  202,  205,  203,  184,

      262,  262,  262,  213,  218,  213,  212,  206,  214,  214,
      214,  214,  215,  211,  215,  207,  189,  216,  216,  216,
      216,  195,  195,  195,  195,  182,   90,   90,   90,  199,
      199,  199,  180,  179,  217,   91,  217,  172,   91,   90,
       90,   90,   90,   90,   90,  286,  286,  286,   91,  172,
      165,   91,  217,  165,  217,   90,   90,   90,  214,  214,
      214,  214,  159,   93,   91,  216,  216,  216,  216,  153,
      151,  233,  110,  233,   90,   90,   90,  216,  216,  216,
      216,  219,  150,   91,   90,   90,   90,   57,  220,  233,
      234,  233,  234,   91,  143,  142,  226,  244,  244,  244,

       90,   90,   90,   90,   90,   90,   91,  229,  234,   91,
      234,  136,   91,  244,  244,  244,  227,   90,   90,   90,
      270,  270,   91,  235,  124,  123,   91,   90,   90,   90,
      110,   90,   90,   90,  103,   95,   91,   87,   82,  243,
       91,   59,  230,   58,  248,  262,  262,  262,  280,  280,
      280,   57,  256,  280,  280,  280,   48,   91,   90,   90,
       90,  304,   91,  304,   90,   90,   90,   91,  304,  257,
      304,  304,  268,   91,  304,  260,  229,  286,  286,  286,
      300,  300,  300,  304,   90,   90,   90,  304,  272,  271,
      271,  271,  271,   91,  298,  298,  298,  300,  300,  300,

      271,  271,  271,  299,  274,  282,  289,  304,  304,  304,
      287,  230,  298,  298,  298,  271,  271,  271,  271,  271,
      271,  299,  304,  304,  304,  304,  294,  304,  304,  304,
      304,  304,  304,  291,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  202,   49,   49,  304,   49,   49,
       49,   49,   49,   49,   56,   56,  304,   56,  304,   56,
       56,   56,   56,   92,   92,  304,  304,  304,   92,   92,
       92,  111,  111,  304,  111,  111,  111,  111,  111,  111,
       49,   49,  304,   49,  304,   49,   56,   56,  304,   56,

      304,   56,  127,  127,  304,  127,  127,  127,  127,  127,
      127,  137,  137,  137,  156,  156,  158,  158,  166,  166,
      228,  228,  304,  228,  228,  228,  228,  228,  228,  231,
      231,  304,  231,  231,  231,  231,  231,  231,  245,  245,
      304,  245,  245,  245,  245,  245,  245,  228,  228,  304,
      228,  304,  228,  259,  259,    3,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,

      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304
    } ;

static const flex_int16_t yy_chk[1025] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    8,
        9,    9,   10,    2,   15,   41,   18,   17,   18,   18,
       18,   18,   24,   26,   26,   19,   15,   17,   17,   10,
       19,  302,   28,   28,   28,    2,  117,   24,   19,   24,

       24,   28,    2,   46,    8,   20,   49,   20,   20,   20,
       20,  117,   29,   29,   29,   41,   29,  132,   75,   20,
       29,   29,   20,   33,   33,   33,   20,   20,  301,   34,
       34,   34,   33,   35,   35,   35,   75,   20,   34,  132,
       20,   49,   35,  296,   36,   36,   36,   71,   20,   46,
       56,   20,   21,   36,   21,   21,   21,   21,   37,   37,
       37,   39,   39,   39,  293,   33,   21,   37,   80,   21,
       39,   71,   34,   21,   38,   38,   38,  292,   38,   93,
       35,   56,   38,   38,   21,   44,   80,   21,   51,   51,
       44,  291,  166,   38,  108,   21,   47,   47,   47,   50,

       50,   50,  170,   50,  112,   47,   36,  167,   39,   57,
       57,  166,   44,   37,   93,   66,   66,   66,   66,   44,
      170,   70,   70,   70,   70,   77,  167,   66,   66,   47,
       66,   50,   51,   70,   70,   50,   70,   74,   79,   77,
      108,   74,   79,  138,  187,   66,   66,   77,   66,  290,
      112,   70,   70,   57,   70,   81,   72,   50,   72,   72,
       72,   72,  288,   74,   79,  138,   73,  180,   73,   81,
       72,   73,   73,   73,   73,  187,  180,   81,   90,   90,
       90,   92,   92,   92,   96,   96,   96,   90,   72,  287,
       92,  118,  285,   96,   97,   97,   97,   98,   98,   98,

       99,   99,   99,   97,  118,  118,   98,  284,  281,   99,
      100,  100,  100,  101,  101,  101,  106,  101,  110,  100,
      276,  106,  101,  102,  102,  102,  118,   96,  185,  115,
      115,  115,  102,  115,  171,  110,  110,  110,  110,   97,
      114,  114,  114,  106,  192,  121,  155,  274,  171,  114,
      106,   99,  273,  100,  121,  121,  171,   98,  269,  155,
      155,  115,  125,  185,  125,  115,  192,  125,  125,  125,
      125,  130,  130,  130,  130,  114,  121,  128,  102,  128,
      267,  155,  128,  128,  128,  128,  266,  115,  131,  131,
      131,  131,  137,  144,  144,  144,  145,  145,  145,  265,

      168,  131,  144,  131,  168,  145,  146,  146,  146,  137,
      264,  208,  137,  137,  157,  146,  147,  147,  147,  131,
      208,  131,  263,  157,  157,  147,  168,  137,  148,  148,
      148,  137,  149,  149,  149,  137,  152,  148,  154,  154,
      154,  149,  181,  145,  261,  157,  181,  154,  201,  257,
      144,  255,  254,  152,  152,  152,  152,  160,  160,  160,
      160,  161,  161,  161,  161,  201,  210,  147,  162,  162,
      162,  162,  253,  148,  161,  228,  161,  252,  163,  163,
      163,  163,  194,  194,  194,  194,  173,  173,  173,  149,
      156,  163,  161,  163,  161,  173,  251,  249,  174,  174,

      174,  210,  225,  156,  156,  156,  156,  174,  242,  163,
      228,  163,  225,  241,  156,  156,  156,  176,  176,  176,
      213,  213,  213,  213,  240,  156,  176,  239,  270,  156,
      156,  156,  156,  156,  156,  158,  230,  230,  238,  175,
      175,  175,  237,  173,  158,  158,  158,  158,  175,  236,
      177,  177,  177,  224,  246,  158,  158,  158,  223,  177,
      178,  178,  178,  270,  176,  222,  158,  246,  246,  178,
      158,  158,  158,  158,  158,  158,  169,  221,  169,  220,
      230,  169,  169,  169,  169,  212,  203,  175,  202,  246,
      183,  183,  183,  200,  197,  175,  175,  177,  175,  183,

      250,  250,  250,  190,  196,  190,  189,  178,  190,  190,
      190,  190,  191,  182,  191,  179,  159,  191,  191,  191,
      191,  195,  195,  195,  195,  153,  198,  198,  198,  199,
      199,  199,  151,  150,  195,  198,  195,  141,  199,  204,
      204,  204,  205,  205,  205,  279,  279,  279,  204,  140,
      135,  205,  195,  134,  195,  206,  206,  206,  214,  214,
      214,  214,  123,  116,  206,  215,  215,  215,  215,  113,
      109,  214,  107,  214,  219,  219,  219,  216,  216,  216,
      216,  198,  103,  219,  226,  226,  226,   94,  199,  214,
      216,  214,  216,  226,   89,   85,  204,  227,  227,  227,

      235,  235,  235,  243,  243,  243,  227,  258,  216,  235,
      216,   76,  243,  244,  244,  244,  206,  248,  248,  248,
      258,  258,  244,  219,   65,   58,  248,  256,  256,  256,
       45,  260,  260,  260,   40,   32,  256,   25,   22,  226,
      260,   14,  258,   12,  235,  262,  262,  262,  268,  268,
      268,   11,  243,  280,  280,  280,    7,  268,  272,  272,
      272,    3,  280,    0,  282,  282,  282,  272,    0,  244,
        0,    0,  256,  282,    0,  248,  259,  286,  286,  286,
      295,  295,  295,    0,  289,  289,  289,    0,  260,  259,
      259,  259,  259,  289,  294,  294,  294,  300,  300,  300,

      259,  259,  259,  294,  262,  272,  282,    0,    0,    0,
      280,  259,  298,  298,  298,  259,  259,  259,  259,  259,
      259,  298,    0,    0,    0,    0,  289,    0,    0,    0,
        0,    0,    0,  286,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  300,  305,  305,    0,  305,  305,
      305,  305,  305,  305,  306,  306,    0,  306,    0,  306,
      306,  306,  306,  307,  307,    0,    0,    0,  307,  307,
      307,  308,  308,    0,  308,  308,  308,  308,  308,  308,
      309,  309,    0,  309,    0,  309,  310,  310,    0,  310,

        0,  310,  311,  311,    0,  311,  311,  311,  311,  311,
      311,  312,  312,  312,  313,  313,  314,  314,  315,  315,
      316,  316,    0,  316,  316,  316,  316,  316,  316,  317,
      317,    0,  317,  317,  317,  317,  317,  317,  318,  318,
        0,  318,  318,  318,  318,  318,  318,  319,  319,    0,
      319,    0,  319,  320,  320,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,

      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[80] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 
        };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tokens.lex"
/**
# Lexer for Basilisk C

Closely based on the [C99 lexer](c.lex). */
#line 33 "tokens.lex"
#include <stdio.h>
#include <assert.h>
#include "parser.h"
#include "basilisk.h"
#include "symbols.h"
	   
#define YYSTYPE Ast *
#define YY_DECL int yylex (YYSTYPE * yylval_param, AstRoot * parse)
 
static void comment (void);
static void preproc (void);
static void bpreproc (void);
static void ompreproc (void);
static void file_line (AstRoot * parse, const char * text);
static int  check_type (AstRoot * parse, bool call);

static Ast * new_ast (AstRoot * parse,
		      int token, int line, char * start, char * end)
{
  Allocator * alloc = parse->alloc;
  Ast * n = allocate (alloc, sizeof(AstTerminal));
  memset (n, 0, sizeof(AstTerminal));
  n->sym = token_symbol (token);
  AstTerminal * t = ast_terminal (n);
  t->start = start;
  t->after = end;
  t->file = parse->file;
  while (start != end) {
    if (*start == '\n')
      line--;
    start++;
  }
  t->line = line;
  return n;
}

#define CAST()								\
  *yylval = new_ast (parse, yytext[0], yylineno, yytext, yytext);	\
  return yytext[0];
  
#define SAST(t) 							\
  *yylval = new_ast (parse, t, yylineno, yytext, yytext + strlen(yytext) - 1); \
  return t;
  
#line 916 "tokens.c"
#line 917 "tokens.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

YYSTYPE * yyget_lval ( void );

void yyset_lval ( YYSTYPE * yylval_param  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param );

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
        YYSTYPE * yylval;
    
    yylval = yylval_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 79 "tokens.lex"


#line 1154 "tokens.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 305 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 956 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 81 "tokens.lex"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 82 "tokens.lex"
{ /* consume //-comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 83 "tokens.lex"
{ file_line (parse, yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 84 "tokens.lex"
{ preproc(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 85 "tokens.lex"
{ bpreproc(); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 86 "tokens.lex"

	YY_BREAK
case 7:
YY_RULE_SETUP
#line 87 "tokens.lex"
{ ompreproc(); }
	YY_BREAK
/* Basilisk C tokens */
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 91 "tokens.lex"
{ SAST(NEW_FIELD); }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 92 "tokens.lex"
{ SAST(NEW_FIELD); }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 93 "tokens.lex"
{ SAST(NEW_FIELD); }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 94 "tokens.lex"
{ SAST(TYPEDEF_NAME); }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 95 "tokens.lex"
{ SAST(TYPEDEF_NAME); }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 96 "tokens.lex"
{ SAST(TYPEDEF_NAME); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 97 "tokens.lex"
{ SAST(MAYBECONST); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 98 "tokens.lex"
{ SAST(TRACE); }
	YY_BREAK
/* GCC extensions */
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 102 "tokens.lex"
{ ompreproc(); }
	YY_BREAK
/* End of GCC extensions */
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 106 "tokens.lex"
{ SAST(check_type (parse, true)); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 107 "tokens.lex"
{ SAST(check_type (parse, false)); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 109 "tokens.lex"
{ SAST(I_CONSTANT); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 110 "tokens.lex"
{ SAST(I_CONSTANT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 111 "tokens.lex"
{ SAST(I_CONSTANT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 112 "tokens.lex"
{ SAST(I_CONSTANT); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 114 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 115 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 116 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 117 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 118 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 119 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 121 "tokens.lex"
{ SAST(STRING_LITERAL); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 123 "tokens.lex"
{ SAST(ELLIPSIS_MACRO); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 124 "tokens.lex"
{ SAST(ELLIPSIS); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 125 "tokens.lex"
{ SAST(RIGHT_ASSIGN); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 126 "tokens.lex"
{ SAST(LEFT_ASSIGN); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 127 "tokens.lex"
{ SAST(ADD_ASSIGN); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 128 "tokens.lex"
{ SAST(SUB_ASSIGN); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 129 "tokens.lex"
{ SAST(MUL_ASSIGN); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 130 "tokens.lex"
{ SAST(DIV_ASSIGN); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 131 "tokens.lex"
{ SAST(MOD_ASSIGN); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 132 "tokens.lex"
{ SAST(AND_ASSIGN); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 133 "tokens.lex"
{ SAST(XOR_ASSIGN); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 134 "tokens.lex"
{ SAST(OR_ASSIGN); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 135 "tokens.lex"
{ SAST(RIGHT_OP); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 136 "tokens.lex"
{ SAST(LEFT_OP); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 137 "tokens.lex"
{ SAST(INC_OP); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 138 "tokens.lex"
{ SAST(DEC_OP); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 139 "tokens.lex"
{ SAST(PTR_OP); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 140 "tokens.lex"
{ SAST(AND_OP); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 141 "tokens.lex"
{ SAST(OR_OP); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 142 "tokens.lex"
{ SAST(LE_OP); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 143 "tokens.lex"
{ SAST(GE_OP); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 144 "tokens.lex"
{ SAST(EQ_OP); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 145 "tokens.lex"
{ SAST(NE_OP); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 146 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 147 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 148 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 149 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 150 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 151 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 152 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 153 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 154 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 155 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 156 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 157 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 158 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 159 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 160 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 161 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 162 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 163 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 164 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 165 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 166 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 167 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 168 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 169 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 171 "tokens.lex"
{ /* whitespace separates tokens */ }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 172 "tokens.lex"
{ /* discard bad characters */ }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 174 "tokens.lex"
ECHO;
	YY_BREAK
#line 1653 "tokens.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 305 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 305 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 304);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 174 "tokens.lex"


static void comment (void)
{
  int c;  
  while ((c = input()) != 0)
    if (c == '*') {
      while ((c = input()) == '*')
	;
      
      if (c == '/')
	return;
      
      if (c == 0)
	break;
    }
  //  yyerror ("unterminated comment");
}

static void preproc (void)
{
  int c, c1 = 0;
  while ((c = input()) != 0) {
    if (c == '\n' && c1 != '\\')      
      return;
    c1 = c;
  }
  //  yyerror ("unterminated preprocessor directive");
}

static void bpreproc (void)
{
  int c;
  while ((c = input()) != 0)
    if (c == '@')
      return;
  //  yyerror ("unterminated @def");
}

static void ompreproc (void)
{
  int c, scope = 1;
  while ((c = input()) != 0) {
    if (c == '(')
      scope++;
    else if (c == ')') {
      scope--;
      if (scope == 0)
	return;
    }
  }
  //  yyerror ("unterminated OMP");
}

static void file_line (AstRoot * parse, const char * text)
{
  char * s = strchr (text, '#') + 1;
  yylineno = atoi(s) - 1;
  s = strchr (s, '"') + 1;
  char * end = strchr (s, '"');
  parse->file = allocate (parse->alloc, end - s + 1);
  strncpy ((char *) parse->file, s, end - s);
  //  fprintf (stderr, "%s: \"%s\" %d\n", text, file, yylineno);
}

static int check_type (AstRoot * parse, bool call)
{
  typedef struct {
    const char * name;
    int type;
  } Type;
  static Type types[] = {
    {"auto",	       AUTO},
    {"break",	       BREAK},
    {"case",	       CASE},
    {"char",	       CHAR},
    {"const",	       CONST},
    {"continue",       CONTINUE},
    {"default",	       DEFAULT},
    {"do",	       DO},
    {"double",	       DOUBLE},
    {"else",	       ELSE},
    {"enum",	       ENUM},
    {"extern",	       EXTERN},
    {"float",	       FLOAT},
    {"for",	       FOR},
    {"goto",	       GOTO},
    {"if",	       IF},
    {"inline",	       INLINE},
    {"int",	       INT},
    {"long",	       LONG},
    {"register",       REGISTER},
    {"restrict",       RESTRICT},
    {"return",	       RETURN},
    {"short",	       SHORT},
    {"signed",	       SIGNED},
    {"sizeof",	       SIZEOF},
    {"static",	       STATIC},
    {"struct",	       STRUCT},
    {"switch",	       SWITCH},
    {"typedef",	       TYPEDEF},
    {"union",	       UNION},
    {"unsigned",       UNSIGNED},
    {"void",	       VOID},
    {"volatile",       VOLATILE},
    {"while",          WHILE},
    {"_Alignas",       ALIGNAS},
    {"_Alignof",       ALIGNOF},
    {"_Atomic",        ATOMIC},
    {"_Bool",          BOOL},
    {"_Complex",       COMPLEX},
    {"complex",        COMPLEX},
    {"_Generic",       GENERIC},
    {"_Imaginary",     IMAGINARY},
    {"_Noreturn",      NORETURN},
    {"_Static_assert", STATIC_ASSERT},
    {"_Thread_local",  THREAD_LOCAL},
    {"__func__",       FUNC_NAME},

                        /* Basilisk C tokens */
    
    {"reduction", REDUCTION},
    {"foreach_dimension", FOREACH_DIMENSION},
    
    {NULL}};
  for (Type * t = types; t->name; t++)
    if (!strcmp (yytext, t->name))
      return t->type;

  if (!strncmp (yytext, "macro", 5)) {
    char * s;
    for (s = yytext + 5; *s != '\0' && *s >= '0' && *s <= '9'; s++);
    if (*s == '\0')
      return MACRODEF;
  }
  
  if (parse->type_already_specified)
    return IDENTIFIER;
  
  return ast_identifier_parse_type (parse->stack, yytext, call, parse->file, yylineno);
}

void lexer_setup (char * buffer, size_t len)
{
  yylineno = 1;
  yy_scan_buffer (buffer, len);
}

