#!/usr/bin/env python3
"""Apply the declared method-host changes to the official oscillation source."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


INCLUDE_START = "#if MOMENTUM\n"
INCLUDE_END = "#endif // standard centered Navier--Stokes solver\n"
METHOD_INCLUDES = """#include \"navier-stokes/centered.h\"
#define FILTERED 1

int oscillation_redistance_imax = 3;
#include \"two-phase-clsvof.h\"

#ifndef METHOD_NN
# define METHOD_NN 0
#endif
#if METHOD_NN
# include \"oscillation_raw27_adapter.h\"
#endif
#include \"integral.h\"
"""

LEVEL_DECLARATION = """#ifndef LEVEL
# define LEVEL 6
#endif"""

RUNTIME_IMAX = """  char * redistance_imax_text = getenv (\"OSCILLATION_REDISTANCE_IMAX\");
  if (redistance_imax_text) {
    char * end = NULL;
    long value = strtol (redistance_imax_text, &end, 10);
    if (!end || *end || !((value >= 0 && value <= 5) ||
                          value == 10 || value == 15 || value == 20)) {
      fprintf (stderr, \"invalid OSCILLATION_REDISTANCE_IMAX=%s\\n\",
               redistance_imax_text);
      return 2;
    }
    oscillation_redistance_imax = value;
  }

"""

LOOP_START = "  for (LEVEL = 4; LEVEL <= 7; LEVEL++) {\n"
LOOP_END_MARKER = "\n  /**\n  We use *grep* to filter the lines generated by gnuplot"
SINGLE_LEVEL_RUN = """  N = 1 << LEVEL;

  /**
  We open a file indexed by the level to store the time evolution of
  the kinetic energy. */

  char name[80];
  sprintf (name, \"k-%d\", LEVEL);
  fp = fopen (name, \"w\");
  run();
  fclose (fp);
"""

TERMINATION_EVENT = r'''

/* Observational only: records the solver's actual end state without adding
   a scheduled time or changing the official integration horizon. */
event generated_termination_record (t = end, last)
{
  FILE * termination_fp = fopen ("termination.csv", "w");
  if (!termination_fp) {
    perror ("termination.csv");
    exit (1);
  }
  fprintf (termination_fp, "reason,requested_terminal_time,actual_terminal_time,iteration\n");
  fprintf (termination_fp, "fixed_time_limit,1,%.17g,%d\n", t, i);
  fclose (termination_fp);
}
'''


def sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def replace_once(source: str, target: str, replacement: str) -> str:
    if source.count(target) != 1:
        raise ValueError(f"expected one occurrence of {target!r}")
    return source.replace(target, replacement, 1)


def build(source: str) -> str:
    include_start = source.index(INCLUDE_START)
    include_end = source.index(INCLUDE_END, include_start) + len(INCLUDE_END)
    source = source[:include_start] + METHOD_INCLUDES + source[include_end:]
    source = replace_once(source, "int LEVEL;", LEVEL_DECLARATION)
    source = replace_once(source, "int main()\n{\n", "int main()\n{\n\n" + RUNTIME_IMAX)
    source = replace_once(
        source,
        "  f.sigma = 1.;",
        "  const scalar sigma[] = 1.;\n  d.sigmaf = sigma;",
    )
    loop_start = source.index(LOOP_START)
    loop_end = source.index(LOOP_END_MARKER, loop_start)
    source = source[:loop_start] + SINGLE_LEVEL_RUN + source[loop_end:]
    source = replace_once(
        source,
        "  fraction (f, D/2.*(1. + 0.05*cos(2.*atan2(y,x))) - sqrt(sq(x) + sq(y)));",
        "  foreach()\n"
        "    d[] = D/2.*(1. + 0.05*cos(2.*atan2(y,x))) - sqrt(sq(x) + sq(y));",
    )
    source = replace_once(source, "\n#if TREE\n", TERMINATION_EVENT + "\n#if TREE\n")
    return source


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--provenance", type=Path, required=True)
    args = parser.parse_args()
    source = args.source.read_text(encoding="utf-8")
    output = build(source)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")
    args.provenance.write_text(
        json.dumps(
            {
                "source": "basilisk/src/test/oscillation.c",
                "source_sha256": sha256(source),
                "generated_sha256": sha256(output),
                "allowed_changes": [
                    "single_level_host",
                    "runtime_redistance_imax",
                    "clsvof_or_nn_method",
                    "observational_terminal_record",
                ],
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
